spring:
  datasource:
    inner:
      jdbc-url: jdbc:mysql://:9095/rescue_wshuttle_test?zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: rootpwd
    outer:
      jdbc-url: jdbc:postgresql://192.168.2.233:5432/smzdm
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: rootpwd